/**
 * Figma Setup Script
 *
 * Configures the Figma file for design system extraction.
 *
 * Usage:
 *   npm run design:setup
 *
 * Then follow the prompts.
 */

import fs from 'fs';
import path from 'path';
import readline from 'readline';

const OUTPUT_DIR = path.resolve(__dirname, '../design-system');

async function prompt(question: string): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function extractFileKey(url: string): string | null {
  // Figma URL formats:
  // https://www.figma.com/file/ABC123/Name
  // https://www.figma.com/design/ABC123/Name
  const match = url.match(/figma\.com\/(?:file|design)\/([a-zA-Z0-9]+)/);
  return match ? match[1] : null;
}

async function main() {
  console.log('🎨 Figma Design System Setup\n');

  // Get Figma URL
  console.log('Paste your Figma file URL:');
  console.log('(e.g., https://www.figma.com/design/ABC123/My-Design-System)\n');

  const url = await prompt('URL: ');

  if (!url) {
    console.error('No URL provided. Exiting.');
    process.exit(1);
  }

  const fileKey = extractFileKey(url);
  if (!fileKey) {
    console.error('Invalid Figma URL. Could not extract file key.');
    console.error('Expected format: https://www.figma.com/design/FILE_KEY/Name');
    process.exit(1);
  }

  console.log(`\n✓ File key: ${fileKey}`);

  // Create config
  const config = `# Figma Design System Source
# Generated by: npm run design:setup

fileKey: "${fileKey}"
fileUrl: "${url}"
lastSync: null
`;

  // Ensure directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  // Write config
  const configPath = path.join(OUTPUT_DIR, 'figma.yaml');
  fs.writeFileSync(configPath, config);

  console.log(`✓ Config saved to: design-system/figma.yaml\n`);

  console.log('Next steps:');
  console.log('1. Get your Figma API token from: https://www.figma.com/settings');
  console.log('2. Run: FIGMA_TOKEN=your-token npm run design:extract');
  console.log('\nOr set FIGMA_TOKEN in .env.local for persistent use.');
}

main().catch(console.error);
